AllCops:
  TargetRubyVersion: 2.6
Style/Documentation:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/WordArray:
  EnforcedStyle: brackets
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'lib/spec/**/*'
    - 'actuators/automatching/spec/**/*'
    - 'scripts/**/*'
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/DotPosition:
  EnforcedStyle: trailing
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true